In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

tf.enable_eager_execution()

In [ ]:
* layer : 유용한 연산자의 집합 
    
* 케라스에 미리 구성되어 잇는 층 
    - dense : 완전 연결 층 
    - Conv2D
    - LSTM
    - BatchNormalication 
    - Dropout 
    

In [24]:
# tf.keras.layers 패키지에서 층은 객체입니다. 층을 구성하려면 간단히 객체를 생성하십시오.
# 대부분의 layer는 첫번째 인수로 출력 차원(크기) 또는 채널을 취합니다.
layer = tf.keras.layers.Dense(100)

# 입력 차원의 수는 층을 처음 실행할 때 유추할 수 있기 때문에 종종 불필요합니다. 
# 일부 복잡한 모델에서는 수동으로 입력 차원의 수를 제공하는것이 유용할 수 있습니다.

# 10은 출력을 나타냄 

layer = tf.keras.layers.Dense(10, input_shape=(None, 7))

In [25]:
# 층을 사용하려면, 호출 해야함

layer(tf.zeros([10,7]))

<tf.Tensor: id=269, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
# layer는 유용한 메서드를 많이 가지고 있음 
 # ex) layer.variables : 층안에 있는 모든 변수를 확인 

# 완전연결층 (Dense)층은 가중치와 편향을 위한 변수를 가짐 

layer.variables

[<tf.Variable 'dense_15/kernel:0' shape=(7, 10) dtype=float32, numpy=
 array([[-0.24468443,  0.36570823, -0.50602806,  0.0409928 ,  0.25654352,
         -0.17692274,  0.36559206, -0.28704438, -0.4708591 , -0.1436069 ],
        [ 0.3964762 , -0.06430972,  0.10296065,  0.3344503 , -0.40664467,
          0.20018202, -0.32130313,  0.05540627, -0.43519837, -0.05430573],
        [ 0.5062207 ,  0.4942273 , -0.47166973,  0.49318624,  0.23126596,
          0.24378711, -0.1921233 , -0.38863578, -0.36614293, -0.3132553 ],
        [-0.39328545, -0.23518479,  0.21211094,  0.4652133 ,  0.5241786 ,
         -0.06512135,  0.0276795 ,  0.4341718 , -0.05079955,  0.36884207],
        [-0.06920916, -0.38888633, -0.12757474, -0.4586153 , -0.01599133,
          0.27863252, -0.47755876,  0.03030252, -0.50509095,  0.19988269],
        [-0.13910961,  0.4225527 , -0.06560522, -0.40528208, -0.39774817,
         -0.3917155 , -0.35198683, -0.22009939,  0.13298136,  0.02105629],
        [-0.5216981 ,  0.33309847,  

In [17]:
# 변수는 객체의 속성을 통해 편리하게 접근 가능 

layer.bias

<tf.Variable 'dense_9/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [35]:
# 사용자 정의 층 구현하기 

class MyDenseLayer(tf.keras.layers.Layer):
    
    # __init__ : 층에 필요한 매개변수를 입력 받음 
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    # build : 입력 텐서의 크기를 알고 나머지를 초기화 할 수 있음 
    def build(self, input_shape):
        print(input_shape)
        self.kernel = self.add_variable("kernel", shape=[int(input_shape[-1]), self.num_outputs])
        print(input_shape[-1], self.num_outputs)
        print(layer.kernel)
        print(input_shape)
    
    # call : 정방향 연산(forward computation) 진행 가능 
    def call(self, input):
        return tf.matmul(input, self.kernel)
    

layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

(10, 5)
5 10
<tf.Variable 'my_dense_layer_8/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.36545092,  0.07518017, -0.2178407 ,  0.16378689, -0.11743248,
        -0.06988668, -0.1886259 , -0.3557327 ,  0.01777667,  0.14509684],
       [-0.20203093, -0.6170791 , -0.5451358 ,  0.3793344 , -0.6084333 ,
        -0.13391978,  0.42714995,  0.4112684 , -0.57350755, -0.23149347],
       [ 0.35965234,  0.23762834,  0.11156452, -0.3158066 ,  0.49690932,
         0.22180212,  0.3438124 , -0.30851158,  0.51698107,  0.14362997],
       [-0.4153428 ,  0.03042698, -0.09771818,  0.01686412,  0.20391762,
         0.07340413,  0.43899232,  0.07386935,  0.5109635 , -0.32636908],
       [ 0.2731306 ,  0.06507546, -0.09583074,  0.5048345 ,  0.09806168,
         0.29162621, -0.22845295, -0.5382868 ,  0.1399355 ,  0.0825358 ]],
      dtype=float32)>
(10, 5)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 

In [39]:
# 머신러닝 모델에의 많은 것은 기존 층을 조합하여 구현된다. 

# 레스넷(resnet)의 각 잔여 블록(residual block)은 합성곱(convolution), 배치 정규화(batch normalization), 쇼트컷(shortcut) 등으로 구성

# 다른층을 포함한 모델을 만들기 위해 사용하는 메인 클래스는 tf.keras.Model 이다. 
# tf.keras.Model을 상송하여 구현해보자 

class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    # https://tykimos.tistory.com/12 참고
    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)

    
block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_1/conv2d_6/kernel:0', 'resnet_identity_block_1/conv2d_6/bias:0', 'resnet_identity_block_1/batch_normalization_v1_6/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_6/beta:0', 'resnet_identity_block_1/conv2d_7/kernel:0', 'resnet_identity_block_1/conv2d_7/bias:0', 'resnet_identity_block_1/batch_normalization_v1_7/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_7/beta:0', 'resnet_identity_block_1/conv2d_8/kernel:0', 'resnet_identity_block_1/conv2d_8/bias:0', 'resnet_identity_block_1/batch_normalization_v1_8/gamma:0', 'resnet_identity_block_1/batch_normalization_v1_8/beta:0']


In [38]:
# 그러나 대부분의 경우에, 많은 층으로 구성된 모델은 간단하게 연이어 하나의 층으로 호출할 수 있습니다. 이는 tf.keras.Sequential 사용하여 간단한 코드로 구현 가능

my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(2, 1, 
                                                      padding='same'),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(3, (1, 1)),
                               tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=914, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>